# Generated by Django 5.0.6 on 2024-06-17 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_chefrecipe_chef_ssn_alter_chefrecipe_recipe_and_more'),
        ('Orders', '0002_alter_itemrecipe_item_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrecipe',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.item'),
        ),
        migrations.AlterField(
            model_name='itemrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.recipe'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.order'),
        ),
    ]
