# Generated by Django 5.0.6 on 2024-05-25 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Ingredient',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Recipe',
            },
        ),
        migrations.CreateModel(
            name='Storehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_ssn', models.ForeignKey(blank=True, db_column='manager_ssn', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Employees.manager')),
            ],
            options={
                'db_table': 'Storehouse',
            },
        ),
        migrations.CreateModel(
            name='ChefRecipe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chef_ssn', models.OneToOneField(db_column='chef_ssn', on_delete=django.db.models.deletion.DO_NOTHING, to='Employees.chef')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.recipe')),
            ],
            options={
                'db_table': 'chef_Recipe',
                'unique_together': {('chef_ssn', 'recipe')},
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.ingredient')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.recipe')),
            ],
            options={
                'db_table': 'Recipe_Ingredient',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='StorehouseIngredient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.ingredient')),
                ('storehouse', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.storehouse')),
            ],
            options={
                'db_table': 'Storehouse_Ingredient',
                'unique_together': {('storehouse', 'ingredient')},
            },
        ),
    ]
