# Generated by Django 5.0.6 on 2024-05-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefRecipe',
            fields=[
                ('chef_ssn', models.OneToOneField(db_column='chef_ssn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Employees.chef')),
            ],
            options={
                'db_table': 'chef_Recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('unit', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Ingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
            ],
            options={
                'db_table': 'Recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Storehouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Inventory.recipe')),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Recipe_Ingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorehouseIngredient',
            fields=[
                ('storehouse', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Inventory.storehouse')),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Storehouse_Ingredient',
                'managed': False,
            },
        ),
    ]
