# Generated by Django 5.0.6 on 2024-05-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('cateorgy', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('cooking', models.BooleanField()),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordered_at', models.DateField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('order_type', models.IntegerField()),
            ],
            options={
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemRecipe',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Orders.item')),
            ],
            options={
                'db_table': 'Item_Recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Orders.order')),
                ('amount', models.IntegerField()),
                ('rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Order_Item',
                'managed': False,
            },
        ),
    ]
