# Generated by Django 5.0.6 on 2024-05-24 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
        ('Employees', '0001_initial'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cateorgy', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cooking', models.BooleanField()),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'Table',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordered_at', models.DateField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('order_type', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Customers.customer')),
                ('shipper_ssn', models.ForeignKey(blank=True, db_column='shipper_ssn', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Employees.shipper')),
                ('waiter_ssn', models.ForeignKey(blank=True, db_column='waiter_ssn', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Employees.waiter')),
                ('table_number', models.ForeignKey(blank=True, db_column='table_number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Orders.table')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='ItemRecipe',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Orders.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.recipe')),
            ],
            options={
                'db_table': 'Item_Recipe',
                'unique_together': {('item', 'recipe')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Orders.order')),
                ('amount', models.IntegerField()),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Orders.item')),
            ],
            options={
                'db_table': 'Order_Item',
                'unique_together': {('order', 'item')},
            },
        ),
    ]
