# Generated by Django 5.0.6 on 2024-06-17 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
        ('Inventory', '0002_alter_chefrecipe_chef_ssn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefrecipe',
            name='chef_ssn',
            field=models.ForeignKey(db_column='chef_ssn', on_delete=django.db.models.deletion.CASCADE, to='Employees.chef'),
        ),
        migrations.AlterField(
            model_name='chefrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.recipe'),
        ),
        migrations.AlterField(
            model_name='storehouseingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='storehouseingredient',
            name='storehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.storehouse'),
        ),
    ]
